
version: "{build}"
branches:
  only:
    - master
    - /v\d+\..+/
    - /release.*/
artifacts:
  - path: bin\Debug\*.exe
    name: NiceHashBot
    type: zip
  - path: bin\Debug\*.dll
    name: NiceHashBotDll
    type: zip
