
version: "{build}"
branches:
  only:
    - master
    - /v\d+\..+/
    - /release.*/
artifacts:
  - path: bin\$(configuration)\*.exe
    name: NiceHashBot
    type: zip
  - path: bin\$(configuration)\*.dll
    name: NiceHashBotDll
    type: zip
